version: '3'
services:
  single-frontend:
    image: xiaoxiongmao5/xapi-frontend:1.0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"  # 映射容器的80端口到主机的80端口
    restart: always  # 总是重新启动容器
    extra_hosts:
      - "xpi-backend.com:60.204.157.168" # 往容器内/etc/hosts文件中添加记录 
      - "localhost:60.204.157.168"
